package com.aicompanion.nativeapp.ui.theme

import androidx.compose.ui.graphics.Color

data class AppColors(
    val name: String,
    val primary: Color,
    val background: Color,
    val surface: Color,
    val card: Color,
    val cardStroke: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val userBubble: Color,
    val aiBubble: Color,
    val onUserBubble: Color,
    val onAiBubble: Color,
    val danger: Color,
    val success: Color,
)

val ThemePresets = listOf(
    // 0 - 默认紫
    AppColors(
        name = "丁香紫",
        primary = Color(0xFF7C5CF0),
        background = Color(0xFFF8F7FC),
        surface = Color(0xFFFFFFFF),
        card = Color(0xFFF3F0FF),
        cardStroke = Color(0xFFE8E4F9),
        textPrimary = Color(0xFF1A1A2A),
        textSecondary = Color(0xFF6B6B8A),
        userBubble = Color(0xFF7C5CF0),
        aiBubble = Color(0xFFFFFFFF),
        onUserBubble = Color(0xFFFFFFFF),
        onAiBubble = Color(0xFF1A1A2A),
        danger = Color(0xFFE5565C),
        success = Color(0xFF4CAF50),
    ),
    // 1 - 薄荷绿
    AppColors(
        name = "薄荷绿",
        primary = Color(0xFF4DB6AC),
        background = Color(0xFFF5FDFC),
        surface = Color(0xFFFFFFFF),
        card = Color(0xFFEDFBF9),
        cardStroke = Color(0xFFD0F0EB),
        textPrimary = Color(0xFF1A2A28),
        textSecondary = Color(0xFF6B8A85),
        userBubble = Color(0xFF4DB6AC),
        aiBubble = Color(0xFFFFFFFF),
        onUserBubble = Color(0xFFFFFFFF),
        onAiBubble = Color(0xFF1A2A28),
        danger = Color(0xFFE5565C),
        success = Color(0xFF4CAF50),
    ),
    // 2 - 暖橙
    AppColors(
        name = "暖橙色",
        primary = Color(0xFFFF8A65),
        background = Color(0xFFFDF8F6),
        surface = Color(0xFFFFFFFF),
        card = Color(0xFFFFF0EB),
        cardStroke = Color(0xFFFFDCC8),
        textPrimary = Color(0xFF2A1A15),
        textSecondary = Color(0xFF8A6B5E),
        userBubble = Color(0xFFFF8A65),
        aiBubble = Color(0xFFFFFFFF),
        onUserBubble = Color(0xFFFFFFFF),
        onAiBubble = Color(0xFF2A1A15),
        danger = Color(0xFFE5565C),
        success = Color(0xFF4CAF50),
    ),
    // 3 - 天空蓝
    AppColors(
        name = "天空蓝",
        primary = Color(0xFF5B9BD5),
        background = Color(0xFFF6F9FD),
        surface = Color(0xFFFFFFFF),
        card = Color(0xFFEEF4FB),
        cardStroke = Color(0xFFD9E6F6),
        textPrimary = Color(0xFF1A1F2A),
        textSecondary = Color(0xFF6B7A8A),
        userBubble = Color(0xFF5B9BD5),
        aiBubble = Color(0xFFFFFFFF),
        onUserBubble = Color(0xFFFFFFFF),
        onAiBubble = Color(0xFF1A1F2A),
        danger = Color(0xFFE5565C),
        success = Color(0xFF4CAF50),
    ),
    // 4 - 樱花粉
    AppColors(
        name = "樱花粉",
        primary = Color(0xFFFF7EB3),
        background = Color(0xFFFDF6FA),
        surface = Color(0xFFFFFFFF),
        card = Color(0xFFFFF0F8),
        cardStroke = Color(0xFFFFD9ED),
        textPrimary = Color(0xFF2A1A25),
        textSecondary = Color(0xFF8A6B7E),
        userBubble = Color(0xFFFF7EB3),
        aiBubble = Color(0xFFFFFFFF),
        onUserBubble = Color(0xFFFFFFFF),
        onAiBubble = Color(0xFF2A1A25),
        danger = Color(0xFFE5565C),
        success = Color(0xFF4CAF50),
    ),
    // 5 - 暗夜黑
    AppColors(
        name = "暗夜黑",
        primary = Color(0xFFBB86FC),
        background = Color(0xFF121212),
        surface = Color(0xFF1E1E1E),
        card = Color(0xFF2A2A2A),
        cardStroke = Color(0xFF3A3A3A),
        textPrimary = Color(0xFFE1E1E1),
        textSecondary = Color(0xFF9E9E9E),
        userBubble = Color(0xFFBB86FC),
        aiBubble = Color(0xFF2A2A2A),
        onUserBubble = Color(0xFF000000),
        onAiBubble = Color(0xFFE1E1E1),
        danger = Color(0xFFFF5252),
        success = Color(0xFF4CAF50),
    ),
    // 6 - 奶油白
    AppColors(
        name = "奶油白",
        primary = Color(0xFFD4A574),
        background = Color(0xFFFFFBF5),
        surface = Color(0xFFFFFFFF),
        card = Color(0xFFFFF5EB),
        cardStroke = Color(0xFFFFE8C8),
        textPrimary = Color(0xFF2A1F15),
        textSecondary = Color(0xFF8A7560),
        userBubble = Color(0xFFD4A574),
        aiBubble = Color(0xFFFFFFFF),
        onUserBubble = Color(0xFFFFFFFF),
        onAiBubble = Color(0xFF2A1F15),
        danger = Color(0xFFE5565C),
        success = Color(0xFF4CAF50),
    ),
    // 7 - 海军蓝
    AppColors(
        name = "海军蓝",
        primary = Color(0xFF3F51B5),
        background = Color(0xFFF5F6FA),
        surface = Color(0xFFFFFFFF),
        card = Color(0xFFEEF0F8),
        cardStroke = Color(0xFFD1D5E8),
        textPrimary = Color(0xFF1A1D2E),
        textSecondary = Color(0xFF6B7399),
        userBubble = Color(0xFF3F51B5),
        aiBubble = Color(0xFFFFFFFF),
        onUserBubble = Color(0xFFFFFFFF),
        onAiBubble = Color(0xFF1A1D2E),
        danger = Color(0xFFE5565C),
        success = Color(0xFF4CAF50),
    ),
)

fun getOrElse(index: Int, default: () -> AppColors): AppColors {
    return if (index in 0 until ThemePresets.size) ThemePresets[index] else default()
}
